[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "experiments"
version = "0.1.0"
description = "Thesis experiments project"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "networkx",
    "matplotlib",
    "cdlib",
    "pandas"
]

[project.scripts]
experiments = "experiments.__main__:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]